### ISSUE TITLE
Multiple Anchors - Unable to Connect to Tag

### ISSUE THREAD

**Issue by bearman1020** [petex8989/Indoor_Positioning_DW3000#1]
Hi, found the project to be very cool and wanted to give it a try. I followed your initializations instructions for tag and anchor and wanted to check that they were working before moving forward. So far I have not been able to get multiple anchors functional or communicating to each other, any suggestions? I'm new to these boards so any help would be greatly appreciated, I wanted to get a multiple anchor example running before tinkering - Thanks!

![Screenshot 2023-08-22 230156](https://github.com/petex8989/Indoor_Positioning_DW3000/assets/79168487/9eaa4848-e4a4-43bd-9f91-97b253bfd839)

**Comment by petex8989** [comment]
Just to confirm, are you using the ESP32 DW3000 board from makerfabs? If you are, you will also need to change parts of the code to work with your specific hardware setup. You will need to find the mac address for each device and enter it into the variables near the top of each file. In the tag code, it is on lines 81 to 88, and on the anchor code, it is in lines 123 to 126.

**Comment by bearman1020** [comment]
That worked, and changed from the 5.0 GHz to 2.4 GHz wifi so now I'm able to get them online! Thank you for the help

![image](https://github.com/petex8989/Indoor_Positioning_DW3000/assets/79168487/0a730a0c-919a-4d83-a775-4475fbde3c58)

I tried running your Indoor Positioning program since it just needed my IP address updated and kept getting the error shown below for your socket. Any suggestions?

***Local ip:192.168.1.57***
Options:
    1. Indoor Positioning
    2. Add Room
    3. Exit
Enter selection #: 1
Traceback (most recent call last):
  File "c:\Users\Downloads\Indoor_Positioning_DW3000-main\Indoor_Positioning_DW3000-main\Indoor_Positioning\positioning_server.py", line 494, in <module>
    main()
  File "c:\Users\Downloads\Indoor_Positioning_DW3000-main\Indoor_Positioning_DW3000-main\Indoor_Positioning\positioning_server.py", line 485, in main
    draw_room()
  File "c:\Users\Downloads\Indoor_Positioning_DW3000-main\Indoor_Positioning_DW3000-main\Indoor_Positioning\positioning_server.py", line 366, in draw_room
    list, recv_data = read_data()
                      ^^^^^^^^^^^
  File "c:\Users\Downloads\Indoor_Positioning_DW3000-main\Indoor_Positioning_DW3000-main\Indoor_Positioning\positioning_server.py", line 186, in read_data
    data, addr = sock.recvfrom(1024)
                 ^^^^^^^^^^^^^^^^^^^
OSError: [WinError 10022] An invalid argument was supplied
